name: Build and Deploy VuePress Site

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check out the template repository
      - name: Check out template repository
        uses: actions/checkout@v2
        with:
          repository: bcc-code/bcc-docs-template

      # Pull the repository documentation and push it to the source folder
      - name: Check out current repository
        uses: actions/checkout@v2
        with:
          path: source

      # Copy the source documentation to the docs
      # ** TODO: The cp lines below should be modified to copy the .md files you want to include in the documentation 
      # ** The "$GITHUB_WORKSPACE/docs/" folder is the target for documenation (.md) files/folder, and the "$GITHUB_WORKSPACE/docs/.vuepress/public/"
      # ** folder is for static assets (such as logos etc.)
      # ** Remove any lines that aren't relevant.
      - name: List folders
        run: |
          cd source
          cp -r * $GITHUB_WORKSPACE/docs/
          # cp -r public/* $GITHUB_WORKSPACE/docs/.vuepress/public/
          ls

      # Configure parameters for documentation page
      # ** TODO: Consider replacing title with a more friendly name
      # ** The base and repository must match the repository name. Otherwise the page won't be compatibile with the github pages.
      - uses: microsoft/variable-substitution@v1
        with:
          files: "docs/.vuepress/userConfig.json"
        env:
          title: ${{ github.event.repository.name }}
          description: ${{ github.event.repository.description }}
          base: /${{ github.repository }}/
          repo: ${{ github.repository }}

      # Build the VuePress site
      - name: Build VuePress site
        run: npm i && yarn docs:build

      # Deploy build
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          # deploy the default output dir of VuePress
          build_dir: docs/.vuepress/dist
          target_branch: gh-pages
        env:
          # @see https://docs.github.com/en/actions/reference/authentication-in-a-workflow#about-the-github_token-secret
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
